name: Daily Activity
on:
  schedule:
    # Runs every day at 9:00 AM UTC (change time as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  update-activity:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONEL_PAT }}
    
    - name: Update activity file
      run: |
        echo "Activity updated on: $(date '+%Y-%m-%d %H:%M:%S UTC')" >> activity.txt
    
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Daily Activity Bot"
        git add activity.txt
        git commit -m "Daily activity: $(date '+%Y-%m-%d')"
        git push
