name: Daily Contribution Commit

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC daily
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date
        run: echo "Updated at $(date)" >> activity.txt

      - name: Configure Git
        run: |
          git config user.name "Amanjot Singh Saini"
          git config user.email "amanjot1503@gmail.com"

      - name: Commit changes
        run: |
          git add activity.txt
          git commit --author="Amanjot Singh Saini <amanjot1503@gmail.com>" -m "Daily update: $(date)" || echo "No changes to commit"

      - name: Push to GitHub with PAT
        env:
          PERSONAL_PAT: ${{ secrets.PERSONAL_PAT }}
        run: |
          git push https://$PERSONAL_PAT@github.com/AmanjotSinghSaini/activity-log.git HEAD:main
